Repository social-sonar/Socialsonar, pull requests merged in 2024-07, with the labels that each got.

#78 Feature | 75 |Deduplication review
  src/app/contacts-list/page.tsx
  src/components/DuplicatesScreen.tsx
  src/components/GoogleAccountsMenu.tsx
  src/lib/data/common.ts
  src/lib/data/google.ts
Labels: enhancement, bugfix

#92 Feature | 56 | Backup restore calendar
  src/actions/common/contacts-bulkactions.ts
  src/actions/common/delete-account.ts
  src/actions/common/saveContact.ts
  src/actions/google/contacts/integrations.ts
  src/actions/google/events/backupRestore.ts
  src/actions/google/events/scheduler.ts
  src/actions/index.ts
  src/app/my-profile/page.tsx
  src/app/sync/page.tsx
  src/app/u/[id]/events/[duration]/page.tsx
  src/auth.ts
  src/components/BackupDialog.tsx
  src/components/CalendarActionsMenu.tsx
  src/components/ContactDetail.tsx
  src/components/EventDatePicker.tsx
  src/components/EventGenerator.tsx
  src/components/GoogleAccountBackup.tsx
  src/components/GoogleAccountRestore.tsx
  src/components/GoogleAccountsMenu.tsx
  src/components/Header.tsx
  src/components/RestoreDialog.tsx
  src/lib/data/common.ts
  src/lib/data/google/contacts/index.ts
  src/lib/data/google/events/index.ts
  src/lib/data/google/getGoogleAccounts.ts
  src/lib/definitions.ts
  src/lib/utils/common.ts
Labels: Enhancement

#100 Feature | 94 | Home base manager
  .dockerignore
  .env.example
  package.json
  prisma/migrations/20240709215531_users_home_bases/migration.sql
  prisma/migrations/20240711172711_home_base_active_flag_default/migration.sql
  prisma/schema.prisma
  src/app/my-profile/page.tsx
  src/components/LocationPicker.tsx
  src/lib/data/common.ts
  src/lib/data/safeQueries.ts
  src/lib/definitions.ts
Labels: Enhancement

#110 Bugfix | Dismissable banner
  src/app/contacts-list/page.tsx
  src/components/DuplicatesScreen.tsx
Labels: Bugfix

#113 Bugfix | Duplicate resolution enhancement
  src/app/api/contacts-list/route.ts
  src/app/api/handle-duplicates/route.ts
  src/components/DuplicatesScreen.tsx
  src/lib/data/common.ts
  src/lib/data/safeQueries.ts
  src/lib/definitions.ts
  src/lib/utils/common.ts
Labels: Enhancement, Help wanted, Bugfix

#114 Clientside pagination, search and other minor fixes in contactbook
  src/app/contacts-list/page.tsx
  src/components/ContactDetail.tsx
Labels: Enhancement

#109 Feature | Creation of travel events
  prisma/migrations/20240716222534_travel_model/migration.sql
  prisma/schema.prisma
  src/actions/google/events/scheduler.ts
  src/actions/google/events/travels.ts
  src/app/my-profile/page.tsx
  src/components/Button.tsx
  src/components/CalendarActionsMenu.tsx
  src/components/Location.tsx
  src/components/TravelManager.tsx
  src/components/common/auth.tsx
  src/lib/definitions.ts
Labels: Enhancement

#122 84 contact book offer user option after saving a contact
  src/app/contacts-list/page.tsx
  src/components/ContactDetail.tsx
Labels: Enhancement

#130 Feature | Testing
  .github/workflows/tests.yml
  __tests__/actions/google/events/backupRestore.test.ts
  __tests__/actions/google/events/travels.test.ts
  __tests__/components/Button.test.tsx
  __tests__/components/Card.test.js
  __tests__/components/ContactDetailAddress.test.js
  __tests__/components/TravelManager.test.tsx
  __tests__/lib/data/google/events/index.test.ts
  __tests__/lib/data/safeQueries.test.ts
  __tests__/mocks/adapter.ts
  __tests__/mocks/auth.ts
  __tests__/mocks/next-auth-providers-credentials.ts
  __tests__/mocks/next-auth.ts
  jest.config.js
  jest.config.ts
  jest.setup.ts
  package.json
  singleton.ts
  src/actions/google/events/backupRestore.ts
  src/lib/data/google/events/index.ts
Labels: Enhancement, Help wanted
